export const FETCH_CONTENT_NAVBAR = "FETCH_CONTENT_NAVBAR";
export const FETCH_CONTENT_NAVBAR_SUCCESS = "FETCH_CONTENT_NAVBAR_SUCCESS";
export const FETCH_CONTENT_NAVBAR_FAIL = "FETCH_CONTENT_NAVBAR_FAIL";

export const FETCH_LANGUAGES = "FETCH_LANGUAGES";
export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";
export const FETCH_LANGUAGES_FAIL = "FETCH_LANGUAGES_FAIL";

export const FETCH_CONTENT_PLATINUM = "FETCH_CONTENT_PLATINUM";
export const FETCH_CONTENT_PLATINUM_SUCCESS = "FETCH_CONTENT_PLATINUM_SUCCESS";
export const FETCH_CONTENT_PLATINUM_FAIL = "FETCH_CONTENT_PLATINUM_FAIL";