export const FETCH_CONTENT_NAVBAR = "FETCH_CONTENT_NAVBAR";
export const FETCH_CONTENT_NAVBAR_SUCCESS = "FETCH_CONTENT_NAVBAR_SUCCESS";
export const FETCH_CONTENT_NAVBAR_FAIL = "FETCH_CONTENT_NAVBAR_FAIL";

export const FETCH_LANGUAGES = "FETCH_LANGUAGES";
export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";
export const FETCH_LANGUAGES_FAIL = "FETCH_LANGUAGES_FAIL";

export const FETCH_CONTENT_PLATINUM = "FETCH_CONTENT_PLATINUM";
export const FETCH_CONTENT_PLATINUM_SUCCESS = "FETCH_CONTENT_PLATINUM_SUCCESS";
export const FETCH_CONTENT_PLATINUM_FAIL = "FETCH_CONTENT_PLATINUM_FAIL";

export const FETCH_CONTENT_DOLBYATMOS = "FETCH_CONTENT_DOLBYATMOS";
export const FETCH_CONTENT_DOLBYATMOS_SUCCESS = "FETCH_CONTENT_DOLBYATMOS_SUCCESS";
export const FETCH_CONTENT_DOLBYATMOS_FAIL = "FETCH_CONTENT_DOLBYATMOS_FAIL";

export const FETCH_CONTENT_SERVICE = "FETCH_CONTENT_SERVICE";
export const FETCH_CONTENT_SERVICE_SUCCESS = "FETCH_CONTENT_SERVICE_SUCCESS";
export const FETCH_CONTENT_SERVICE_FAIL = "FETCH_CONTENT_SERVICE_FAIL";

export const FETCH_CONTENT_FOOTER = "FETCH_CONTENT_FOOTER";
export const FETCH_CONTENT_FOOTER_SUCCESS = "FETCH_CONTENT_FOOTER_SUCCESS";
export const FETCH_CONTENT_FOOTER_FAIL = "FETCH_CONTENT_FOOTER_FAIL";

export const FETCH_CONTENT_SOCIALMEDIA = "FETCH_CONTENT_SOCIALMEDIA";
export const FETCH_CONTENT_SOCIALMEDIA_SUCCESS = "FETCH_CONTENT_SOCIALMEDIA_SUCCESS";
export const FETCH_CONTENT_SOCIALMEDIA_FAIL = "FETCH_CONTENT_SOCIALMEDIA_FAIL";

export const FETCH_CONTENT_ADVERTISEMENT = "FETCH_CONTENT_ADVERTISEMENT";
export const FETCH_CONTENT_ADVERTISEMENT_SUCCESS = "FETCH_CONTENT_ADVERTISEMENT_SUCCESS";
export const FETCH_CONTENT_ADVERTISEMENT_FAIL = "FETCH_CONTENT_ADVERTISEMENT_FAIL";

export const FETCH_CONTENT_SECONDFOOTER = "FETCH_CONTENT_SECONDFOOTER";
export const FETCH_CONTENT_SECONDFOOTER_SUCCESS = "FETCH_CONTENT_SECONDFOOTER_SUCCESS";
export const FETCH_CONTENT_SECONDFOOTER_FAIL = "FETCH_CONTENT_SECONDFOOTER_FAIL";

export const FETCH_CONTENT_NEWS = "FETCH_CONTENT_NEWS";
export const FETCH_CONTENT_NEWS_SUCCESS = "FETCH_CONTENT_NEWS_SUCCESS";
export const FETCH_CONTENT_NEWS_FAIL = "FETCH_CONTENT_NEWS_FAIL";

export const FETCH_CONTENT_FAQ = "FETCH_CONTENT_FAQ";
export const FETCH_CONTENT_FAQ_SUCCESS = "FETCH_CONTENT_FAQ_SUCCESS";
export const FETCH_CONTENT_FAQ_FAIL = "FETCH_CONTENT_FAQ_FAIL";